// Every ordinary case is executed by Node.js and by compiled Rust.
const main = body => `function main() { ${body} }`;
export const executionCases = [
  ['promoted numeric default', 'function twice(value=1){return value*2;} function main(){console.log(twice(1.5));console.log(twice());}'],

  ['typed string reassignment', 'function main(){let text:string="a";text+="b";text="c";console.log(text);}', 'function main(){let text="a";text+="b";text="c";console.log(text);}'],

  ['typed local passed to inferred function', 'function twice(value){return value*2;} function main(){const value:number=1;console.log(twice(value));}', 'function twice(value){return value*2;} function main(){const value=1;console.log(twice(value));}'],
  ['string array parameter', 'function decorate(values){return values.map(value=>value+"!");} function main(){console.log(decorate(["a","b"]));}'],
  ['boolean array parameter', 'function check(values){return values.every(value=>value);} function main(){console.log(check([true,false]));}'],

  ['variable float argument', 'function twice(value){return value*2;} function main(){const rate=1.5;console.log(twice(rate));}'],
  ['variable string argument', 'function echo(value){return value;} function main(){const word="hello";console.log(echo(word));}'],
  ['variable alias argument', 'function twice(value){return value*2;} function main(){const rate=1.5;const alias=rate;console.log(twice(alias));}'],
  ['forwarded parameter', 'function twice(value){return value*2;} function forward(value){return twice(value);} function main(){const rate=1.5;console.log(forward(rate));}'],
  ['mixed numeric array parameter', 'function total(values){return values.reduce((s,x)=>s+x,0);} function main(){console.log(total([1,1.5]));}'],
  ['return value argument', 'function value(){return 1.5;} function twice(value){return value*2;} function main(){console.log(twice(value()));}'],
  ['typed numeric local', 'function value(){let x: number=1;x=1.5;x+=1;x++;return x;} function main(){console.log(value());}', 'function value(){let x=1;x=1.5;x+=1;x++;return x;} function main(){console.log(value());}'],
  ['typed numeric array', 'function main(){const values: number[]=[1,2];values.push(1.5);console.log(values);}', 'function main(){const values=[1,2];values.push(1.5);console.log(values);}'],
  ['typed default parameter', 'function value(x: number=1){return x+0.5;} function main(){console.log(value());}', 'function value(x=1){return x+0.5;} function main(){console.log(value());}'],

  ['precedence', main('console.log((1 + 2) * 3); console.log(10 - (6 - 2)); console.log(-(1 + 2));')],
  ['division and floor', main('console.log(5 / 2); console.log(Math.floor(-1.5)); console.log(Math.floor(1.9));')],
  ['string return', 'function greet() { return "hello"; } function main() { console.log(greet()); }'],
  ['default parameters', 'function add(x = 10) { return x + 1; } function say(msg = "hi") { return msg; } function main() { console.log(add()); console.log(add(2)); console.log(say()); }'],
  ['float inference', 'function scale(a) { return a * 2; } function main() { console.log(scale(1)); console.log(scale(1.5)); }'],
  ['string escaping', main('console.log("quote: \\\" slash: \\\\ tab: \\t"); console.log(`{value} ${2 + 3}`);')],
  ['switch fallthrough', main('let n = 0; switch (1) { case 1: n += 1; case 2: n += 2; break; default: n += 10; } console.log(n);')],
  ['switch grouped cases', main('let n = 0; switch (2) { case 1: case 2: n = 8; break; } console.log(n);')],
  ['switch default in middle', main('let n = 0; switch (3) { case 1: n += 1; break; default: n += 10; case 3: n += 3; } console.log(n);')],
  ['for continue', main('let n = 0; for (let i = 3; i > 0; i--) { if (i === 2) { continue; } n += i; } console.log(n);')],
  ['for body updates index', main('let n = 0; for (let i = 0; i < 5; i++) { n += i; i += 1; } console.log(n);')],
  ['dynamic for bound', main('let end = 4; let n = 0; for (let i = 0; i < end; i++) { n += i; end -= 1; } console.log(n);')],
  ['map preserves source', main('const a = [1, 2, 3]; const b = a.map(x => x * 2); console.log(b); console.log(a);')],
  ['map index', main('const a = [5, 6]; console.log(a.map((x, i) => x + i));')],
  ['map block return', main('const a = [1, 2]; console.log(a.map(x => { return x + 2; }));')],
  ['map empty', main('const a = []; console.log(a.map(x => x + 1));')],
  ['map strings', main('const a = ["a", "b"]; console.log(a.map(x => x + "!")); console.log(a);')],
  ['reduce initial', main('const a = [1, 2, 3]; console.log(a.reduce((s, x) => s + x, 10)); console.log(a);')],
  ['reduce no initial', main('const a = [2, 3, 4]; console.log(a.reduce((s, x) => s * x));')],
  ['reduce empty with initial', main('const a = []; console.log(a.reduce((s, x) => s + x, 7));')],
  ['reduce single', main('const a = [42]; console.log(a.reduce((s, x) => s + x));')],
  ['reduce index', main('const a = [2, 3, 4]; console.log(a.reduce((s, x, i) => s + x * i, 0)); console.log(a.reduce((s, x, i) => s + x * i));')],
  ['reduce strings', main('const a = ["a", "b"]; console.log(a.reduce((s, x) => s + x, ""));')],
  ['filter and index', main('const a = [1, 4, 3, 8]; console.log(a.filter(x => x > 3)); console.log(a.filter((x, i) => i % 2 === 0)); console.log(a);')],
  ['forEach capture', main('const a = [1, 2, 3]; let sum = 0; a.forEach((x, i) => { sum += x + i; }); console.log(sum); console.log(a);')],
  ['some every', main('const a = [1, 2, 3]; console.log(a.some(x => x > 2)); console.log(a.every(x => x > 0)); console.log(a.some((x, i) => x === i)); console.log(a);')],
  ['some every empty', main('const a = []; console.log(a.some(x => x > 0)); console.log(a.every(x => x > 0));')],
  ['find found and missing', main('const a = [1, 2, 3]; console.log(a.find(x => x > 1)); console.log(a.find(x => x > 9)); console.log(a.find((x, i) => i === 2)); console.log(a);')],
  ['split normal and trailing', main('const text = "a,b,"; console.log(text.split(",")); console.log(text);')],
  ['split empty and omitted', main('const text = "abc"; console.log(text.split("")); console.log(text.split()); const empty = ""; console.log(empty.split("")); console.log(empty.split(","));')],
  ['split limits', main('const text = "a,b,c"; console.log(text.split(",", 2)); console.log(text.split(",", 0)); console.log(text.split(",", -1));')],
  ['split Unicode BMP', main('const text = "台灣"; console.log(text.split("")); console.log(text.length);')],
  ['split method chain', main('const text = "a,b,c"; console.log(text.split(",").map(x => x + "!").join("|"));')],
  ['splice replace and result', main('const a = [1, 2, 3, 4]; const removed = a.splice(1, 2, 8, 9); console.log(a); console.log(removed);')],
  ['splice negative', main('const a = [1, 2, 3, 4]; console.log(a.splice(-2, 1)); console.log(a);')],
  ['splice omitted delete', main('const a = [1, 2, 3]; console.log(a.splice(1)); console.log(a);')],
  ['splice no arguments', main('const a = [1, 2]; console.log(a.splice()); console.log(a);')],
  ['splice clamp and negative delete', main('const a = [1, 2]; console.log(a.splice(20, 8, 9)); console.log(a); console.log(a.splice(-20, -2, 7)); console.log(a);')],
  ['splice source length argument', main('const a = [1, 2, 3]; console.log(a.splice(0, a.length)); console.log(a);')],
  ['splice strings', main('const a = ["a", "b"]; console.log(a.splice(0, 1, "c")); console.log(a);')],
  ['splice empty', main('const a = []; console.log(a.splice(0, 1, 5)); console.log(a);')],
  ['slice clones and clamps', main('const a = [1, 2, 3]; const b = a.slice(-2, 10); b.push(9); console.log(a); console.log(b); console.log(a.slice(2, 1)); console.log(a.slice(-20));')],
  ['push multiple and pop', main('const a = [1]; console.log(a.push(2, 3)); console.log(a.pop()); console.log(a); const b = []; console.log(b.pop());')],
  ['includes and indexOf', main('const a = [1, 2, 1]; console.log(a.includes(1, 1)); console.log(a.includes(1, -1)); console.log(a.indexOf(1, 1)); console.log(a.indexOf(9));')],
  ['includes NaN', main('const a = [1.5, NaN]; console.log(a.includes(NaN)); console.log(a.indexOf(NaN));')],
  ['array join', main('const a = [1, 2, 3]; console.log(a.join()); console.log(a.join("-")); const empty = []; console.log(empty.join(","));')],
  ['string methods', main('const s = " AbC "; console.log(s.trim().toLowerCase()); console.log(s.toUpperCase()); console.log(s.startsWith(" ")); console.log(s.endsWith(" ")); console.log(s.includes("b"));')],
  ['borrowed array methods', 'function total(arr) { return arr.map(x => x + 1).reduce((s, x) => s + x, 0); } function main() { const a = [1, 2]; console.log(total(a)); console.log(a); }'],
  ['mutable array parameter', 'function remove(arr) { return arr.splice(0, 1); } function main() { const a = [1, 2]; console.log(remove(a)); console.log(a); }'],
  ['mutable push parameter', 'function add(arr, x) { arr.push(x); } function main() { const a = [1]; add(a, 2); console.log(a); }'],
  ['push source length', main('const a = [1, 2]; console.log(a.push(a.length)); console.log(a);')],
  ['empty string array', main('const a = []; a.push("a", "b"); console.log(a.map(x => x + "!")); console.log(a);')],
  ['forEach ignores return', main('const a = [1, 2]; a.forEach(x => { console.log(x); return x + 1; }); console.log(a);')],
  ['reduce float without initial', main('const a = [1, 2, 3]; console.log(a.reduce((s, x) => s + x / 2));')],
  ['split explicit undefined', main('const s = "a,b"; console.log(s.split(undefined)); console.log(s.split(",", undefined));')],
  ['reduce float accumulator', main('const a = [1, 2, 3]; console.log(a.reduce((s, x) => s + x / 2, 0));')],
  ['switch variable case', main('const selected = 2; const other = 1; let n = 0; switch(selected) { case other: n = 10; break; case selected: n = 20; break; default: n = 30; } console.log(n);')],
  ['switch conditional break', main('let n = 0; switch(1) { case 1: if (true) { break; } n = 1; break; default: n = 2; } console.log(n);')],
];

export const diagnosticCases = [
  ['callback source mutation', main('const a = [1, 2]; a.map(x => { a.push(x); return x; });'), /Mutating the source array/],
  ['mixed arrays', main('const a = [1, "a"]; console.log(a);'), /Mixed element types/],
  ['unsupported array method', main('const a = [1, 2]; a.flatMap(x => [x]);'), /Unsupported array method: flatMap/],
  ['namespace import', 'import * as math from "./math.js";', /Namespace imports are unsupported/],
  ['try/catch', main('try { console.log(1); } catch(e) { console.log(2); }'), /Unsupported AST node: TryStatement.*source:1:/],
  ['conflicting calls', 'function f(x) { return x; } function main() { f(1); f("x"); }', /Conflicting argument types/],
  ['regexp split', main('const s = "a b"; s.split(/\s+/);'), /split supports string separators/],
  ['callback array parameter', main('const a = [1]; a.map((x, i, array) => x);'), /Array callbacks support/],
  ['external Node module', 'import http from "node:http";', /Unsupported external module/],
];
