const main = body => `function main(){${body}}`;
export const dataExecutionCases = [
  ['narrowed function result stays concrete', 'function value(){const x=[0].pop();return x!==undefined?x:2;}function main(){console.log(value()+1);}'],
  ['nullable conditional narrows result', main('const x=[0].pop();const y=x!=null?x:2;console.log(y+1);console.log(x!=null&&x===0);')],
  ['both strict missing guards', 'function check(x:number|null|undefined):number{if(x!==null&&x!==undefined){return x+1;}return 0;}function main(){console.log(check(null));console.log(check(undefined));console.log(check(0));}', 'function check(x){if(x!==null&&x!==undefined){return x+1;}return 0;}function main(){console.log(check(null));console.log(check(undefined));console.log(check(0));}'],
  ['owned string remains usable in collections', 'function main(){let key:string="a";let value:string="b";const m=new Map<string,string>();m.set(key,value);console.log(key);console.log(value);console.log(m.get(key)??"missing");const s=new Set<string>();s.add(value);console.log(value);}', 'function main(){let key="a";let value="b";const m=new Map();m.set(key,value);console.log(key);console.log(value);console.log(m.get(key)??"missing");const s=new Set();s.add(value);console.log(value);}'],
  ['nullable Map value is flattened', 'function main(){const m=new Map<string,number|null>();m.set("a",null);console.log(m.get("a")==null);console.log(m.get("a")===undefined);console.log(m.get("missing")===undefined);console.log(m.get("a")??4);}', 'function main(){const m=new Map();m.set("a",null);console.log(m.get("a")==null);console.log(m.get("a")===undefined);console.log(m.get("missing")===undefined);console.log(m.get("a")??4);}'],
  ['nullable parameter default', 'function value(x:number|null=null):number{return x??3;}function main(){console.log(value());console.log(value(0));}', 'function value(x=null){return x??3;}function main(){console.log(value());console.log(value(0));}'],
  ['default sort is lexicographic', main('const a=[10,2,1,20];console.log(a.sort());console.log(a);')],
  ['numeric sort and reverse mutate', main('const a=[3,1,2,1];a.sort((a,b)=>a-b);console.log(a);console.log(a.reverse().map(x=>x*2));console.log(a);')],
  ['sort comparator block', main('const a=[4,2,3];a.sort((a,b)=>{return b-a;});console.log(a);')],
  ['UTF16 default sort', main('const a=["\ue000","😀","a","z"];a.sort();console.log(a.join("|"));')],
  ['empty sorting', main('const a=[];console.log(a.sort());console.log(a.reverse());')],
  ['float lexical sort', main('const a=[1e21,1e-7,2,10,0,-0];a.sort();console.log(a.join("|"));')],
  ['flat copies and depth', main('const a=[[[1,2],[3]],[[4],[5,6]]];console.log(a.flat(0));console.log(a.flat());console.log(a.flat(2));console.log(a.flat(Infinity));console.log(a);')],
  ['flat fractional and negative depth', main('const a=[[1],[2,3]];console.log(a.flat(1.8));console.log(a.flat(-1));')],
  ['flat strings', main('const a=[["a"],["b","c"]];console.log(a.flat().map(x=>x+"!"));')],
  ['find guards and coalescing', main('const a=[0,1,2];const found=a.find(x=>x===0);if(found!==undefined){console.log(found+2);}console.log(found??99);const missing=a.find(x=>x===9);console.log(missing??99);console.log(missing===undefined);')],
  ['pop preserves false and zero', main('const a=[0];const value=a.pop();console.log(value??10);console.log(a.pop()??10);const b=[false];console.log(b.pop()??true);')],
  ['pop preserves empty string', main('const a=[""];const x=a.pop();console.log(x??"fallback");if(x!=null){console.log(x.length);}console.log(a.pop()??"fallback");')],
  ['nullable union and guard clause', 'function twice(x:number|null|undefined):number{if(x==null){return 0;}return x*2;}function main(){let x:number|null|undefined=null;console.log(x===undefined);console.log(x===null);console.log(x??4);x=0;console.log(x??4);console.log(twice(null));console.log(twice(3));}', 'function twice(x){if(x==null){return 0;}return x*2;}function main(){let x=null;console.log(x===undefined);console.log(x===null);console.log(x??4);x=0;console.log(x??4);console.log(twice(null));console.log(twice(3));}'],
  ['nullable string truthiness and assignment', 'function main(){let text:string|null|undefined=undefined;console.log(text??"hi");text="";if(text){console.log(text.length);}text="hello";if(text!=null){console.log(text.length);}console.log(null===undefined);console.log(null==undefined);}', 'function main(){let text=undefined;console.log(text??"hi");text="";if(text){console.log(text.length);}text="hello";if(text!=null){console.log(text.length);}console.log(null===undefined);console.log(null==undefined);}'],
  ['coalescing is lazy', main('const a=[0];let calls=0;const value=a.pop();console.log(value??calls++);console.log(calls);')],
  ['Map order and replacement', main('const m=new Map([["b",2],["a",1]]);m.set("b",3);console.log(m.size);console.log(m.get("b")??0);console.log(Array.from(m.keys()));console.log(Array.from(m.values()));console.log(m.delete("b"));m.set("b",4);console.log(Array.from(m.keys()));console.log(m.has("a"));m.clear();console.log(m.size);console.log(m.get("a")??9);')],
  ['empty inferred Map', main('const m=new Map();m.set("a",1).set("b",2);console.log(m.get("a")??0);console.log(m.has("x"));console.log(m.delete("x"));')],
  ['Set order deduplication and chaining', main('const s=new Set([3,1,3,2]);s.add(2).add(4);console.log(s.size);console.log(Array.from(s));console.log(s.delete(1));s.add(1);console.log(Array.from(s.values()));console.log(s.has(9));s.clear();console.log(s.size);')],
  ['empty inferred Set', main('const s=new Set();s.add("a").add("b");console.log(Array.from(s));')],
  ['Map SameValueZero', main('const m=new Map([[NaN,1],[0,2]]);m.set(NaN,3);m.set(-0,4);console.log(m.size);console.log(m.get(NaN)??0);console.log(m.get(0)??0);')],
  ['Set SameValueZero', main('const s=new Set([NaN,NaN,0,-0]);console.log(s.size);console.log(s.has(NaN));console.log(s.delete(-0));console.log(s.has(0));')],
  ['typed collection parameter', 'function read(m:Map<string,number>):number{return m.get("a")??0;}function main(){const m=new Map<string,number>();m.set("a",2);console.log(read(m));console.log(m.size);}', 'function read(m){return m.get("a")??0;}function main(){const m=new Map();m.set("a",2);console.log(read(m));console.log(m.size);}'],
];
export const dataDiagnosticCases = [
  ['mutating array return chain', main('const a=[3,1,2];a.sort().reverse();console.log(a);'), /requires separate statements/],
  ['array identity is not value equality', main('const a=[1];const b=[1];console.log(a===b);'), /Reference identity/],
  ['unrelated comparisons cannot narrow null', 'function f(x:number|null|undefined):number{if(x!==0&&x!==undefined){return x+1;}return 0;}function main(){f(null);}', /Nullable values require a guard/],
  ['live Map iterator is diagnosed', main('const m=new Map([["a",1]]);const keys=m.keys();m.set("b",2);console.log(Array.from(keys));'), /RUST_COLLECTION_ITERATOR/],
  ['sort comparator side effect', main('const a=[1,2];let count=0;a.sort((a,b)=>{count++;return a-b;});'), /RUST_COMPARATOR_EFFECT/],
  ['unguarded nullable arithmetic', main('const x=[1].find(x=>x>2);console.log(x+1);'), /Nullable values require a guard/],
  ['unguarded nullable receiver', main('const x=["a"].pop();console.log(x.length);'), /Nullable receiver requires a guard/],
  ['dynamic flat depth', main('const a=[[1]];let depth=1;console.log(a.flat(depth));'), /flat depth currently requires/],
  ['mutated reverse alias', main('const a=[1,2];const b=a.reverse();b.push(3);console.log(a);'), /RUST_SHARED_ALIAS/],
  ['invalid comparator return', main('const a=[1,2];a.sort((a,b)=>true);'), /comparator must return a number/],
  ['unknown Map operation', main('const m=new Map([["a",1]]);m.entries();'), /RUST_COLLECTION_METHOD/],
  ['typed collection mismatch', 'function main(){const s=new Set<number>();s.add("a");}', /JS_COLLECTION_TYPE/],
  ['untyped empty Map', main('const m=new Map();console.log(m.size);'), /Empty Map requires explicit/],
  ['nonnullable declaration', 'function main(){const x:number=null;}', /JS_DECLARATION_TYPE/],
];
