import fs from 'node:fs';
import vm from 'node:vm';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { transpile } from '../src/index.js';
import { examples } from './docs-examples.js';

const verify = process.argv.includes('--verify');
const generated = {};
const canonical = (line) => {
  try {
    if (line.startsWith('[')) return JSON.stringify(JSON.parse(line));
  } catch {}
  return line;
};
const temp = verify
  ? fs.mkdtempSync(path.join(os.tmpdir(), 'js2rust-docs-'))
  : null;
try {
  for (const [id, example] of Object.entries(examples)) {
    const lines = [];
    vm.runInNewContext(
      `${example.javascript}\nmain();`,
      {
        console: {
          log: (value) =>
            lines.push(
              Array.isArray(value)
                ? JSON.stringify(value).replaceAll(',', ', ')
                : String(value),
            ),
        },
      },
      { timeout: 2000 },
    );
    const rust = transpile(example.javascript);
    const main = rust.slice(rust.lastIndexOf('fn main()')).trim();
    generated[id] = { ...example, rust, main, output: lines.join('\n') };
    if (verify) {
      const file = path.join(temp, `${id}.rs`);
      const executable = path.join(
        temp,
        process.platform === 'win32' ? `${id}.exe` : id,
      );
      fs.writeFileSync(file, rust);
      const compile = spawnSync(
        'rustc',
        ['--edition=2021', '-A', 'warnings', file, '-o', executable],
        { encoding: 'utf8', timeout: 30000 },
      );
      assert.equal(
        compile.status,
        0,
        `Documentation example ${id} failed to compile: ${compile.error || compile.stderr}`,
      );
      const run = spawnSync(executable, [], {
        encoding: 'utf8',
        timeout: 5000,
      });
      assert.equal(
        run.status,
        0,
        `Documentation example ${id} failed to run: ${run.error || run.stderr}`,
      );
      assert.deepEqual(
        run.stdout.trim().split(/\r?\n/).map(canonical),
        lines.map(canonical),
        `Documentation example ${id} differs from JavaScript`,
      );
      console.log(`✓ ${id}: Rust compiled, executed and matched JavaScript`);
    }
  }
  const data = `// Generated by npm run docs:build. Edit scripts/docs-examples.js instead.\nwindow.JS2RUST_EXAMPLES = ${JSON.stringify(generated, null, 2)};\n`;
  const target = new URL('../docs/examples-data.js', import.meta.url);
  if (verify)
    assert.equal(
      fs.readFileSync(target, 'utf8'),
      data,
      'Documentation data is stale. Run npm run docs:build.',
    );
  else {
    fs.writeFileSync(target, data);
    console.log('Built docs/examples-data.js from the project transpiler.');
  }
} finally {
  if (temp) fs.rmSync(temp, { recursive: true, force: true });
}
